/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dsu.se231027.policemanagementsystem.GUI;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hamza Nizamani
 */
public class ViewComplains extends javax.swing.JFrame {
     private final DefaultTableModel ComplainModel;
    
    final private String defaultCSVPathFIR = "Complains.csv";
    
    public boolean debug = true;
    /**
     * Creates new form ViewComplains
     */
    public ViewComplains() {
        
        ComplainModel = new DefaultTableModel();
        checkAndCreateFiles();
        loadDefaultTable();
        initComponents();
    }
    private void loadDefaultTable() {
        File defaultCSVPayroll = new File(defaultCSVPathFIR);
        loadCSVFile(defaultCSVPayroll, ComplainModel);
    }
    
    private void checkAndCreateFiles() {
        checkAndCreateFile(defaultCSVPathFIR, "Case No,Name,CNIC,Type,Phone Number, Email, Address, City, Complaint Type, Complain Details");
    }

    private static void checkAndCreateFile(String filePath, String header) {
        File file = new File(filePath);

        if (!file.exists()) {
            try (FileWriter writer = new FileWriter(file)) {
                writer.write(header);
                System.out.println("File created: " + filePath);
            } catch (IOException e) {
                System.err.println("Error creating file: " + filePath);
            }
        } else {
            System.out.println("File already exists: " + filePath);
        }
    }
    
    private void addNewRow(DefaultTableModel Model) {
        Object[] emptyRow = new Object[Model.getColumnCount()];
        Model.addRow(emptyRow);
    }
    private void saveCSVFile(File file, DefaultTableModel tableModel) {
        try (PrintWriter writer = new PrintWriter(file)) {
            for (int i = 0; i < tableModel.getColumnCount(); i++) {
                writer.print(tableModel.getColumnName(i));
                if (i < tableModel.getColumnCount() - 1) {
                    writer.print(",");
                }
            }
            writer.println();
            for (int i = 0; i < tableModel.getRowCount(); i++) {
                for (int j = 0; j < tableModel.getColumnCount(); j++) {
                    if (tableModel.getValueAt(i, j) != null) {
                        writer.print(tableModel.getValueAt(i, j));
                    } else {
                        writer.print("");
                    }
                    if (j < tableModel.getColumnCount() - 1) {
                        writer.print(",");
                    }
                }
                writer.println();
            }
            JOptionPane.showMessageDialog(this, "Updated Sucessfully!");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving the CSV file.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void loadCSVFile(File file, DefaultTableModel DefRatesModel) {
        
        DefRatesModel.setColumnCount(0); // Clear previous columns
        DefRatesModel.setRowCount(0); // Clear previous data rows

        try (Scanner scanner = new Scanner(file)) {
            if (scanner.hasNextLine()) {
                String[] tableNames = scanner.nextLine().split(",");
                for (String tableName : tableNames) {
                    DefRatesModel.addColumn(tableName);
                    if (debug)
                        System.out.println(tableName);
                }
            }

            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] data = line.split(",");
                DefRatesModel.addRow(data);
                if (debug)
                    System.out.println("->" + line);
            }

        } catch (FileNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reading the CSV file.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header5 = new javax.swing.JPanel();
        TitleText5 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        ButtonCancel5 = new javax.swing.JButton();
        EmpDataTable = new javax.swing.JTable();
        ButtonAddRow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header5.setBackground(java.awt.SystemColor.controlHighlight);
        Header5.setPreferredSize(new java.awt.Dimension(708, 50));

        TitleText5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TitleText5.setForeground(new java.awt.Color(10, 10, 10));
        TitleText5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleText5.setText("Complains");

        jButton9.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton9.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        ButtonCancel5.setText("Go Back");
        ButtonCancel5.setOpaque(true);
        ButtonCancel5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancel5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Header5Layout = new javax.swing.GroupLayout(Header5);
        Header5.setLayout(Header5Layout);
        Header5Layout.setHorizontalGroup(
            Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ButtonCancel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleText5, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Header5Layout.setVerticalGroup(
            Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleText5)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCancel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        EmpDataTable.setModel(ComplainModel);

        ButtonAddRow.setText("Add Row");
        ButtonAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header5, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonAddRow)
                    .addComponent(EmpDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(EmpDataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonAddRow)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ButtonCancel5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancel5ActionPerformed

        dispose();
        new ViewCases().setVisible(true);
    }//GEN-LAST:event_ButtonCancel5ActionPerformed

    private void ButtonAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddRowActionPerformed
       addNewRow(ComplainModel);
    }//GEN-LAST:event_ButtonAddRowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComplains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewComplains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddRow;
    private javax.swing.JButton ButtonCancel5;
    private javax.swing.JTable EmpDataTable;
    private javax.swing.JPanel Header5;
    private javax.swing.JLabel TitleText5;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
